### ISSUE TITLE
language-coffee-script 'Preferred Line Length' as max_line_length

### ISSUE THREAD

**Issue by jajaperson** [AtomLinter/linter-coffeelint#100]
I am aware of all the closed issues regarding `max_line_length`, but this is not an issue but a suggestion. Couldn't the `max_line_length` just default to the `Preferred Line Length` specified in the settings for `language-coffee-script`?

**Comment by Arcanemagus** [comment]
I'm closing this as `wontfix`:

Following the editor setting like that isn't going to change it for anyone _else_ working on the code, unless they also change their editor setting. The entire point of rules like that is that it is a style change that you should decide on for the project.

You don't care at all about the line length? Just turn the rule off.
Don't have a preference, but want _something_ to check? Use the default
Default doesn't work for you? Set a different value for the maximum.

It sounds like you just need to update your `coffeelint.json` file 😉.
