### ISSUE TITLE
Not working with coffeelint.json in project's root

### ISSUE THREAD

**Issue by nickdima** [AtomLinter/linter-coffeelint#22]
It seem that linter is not working at all if I have a local configuration in my project's root.
Without one, it works, but by just copying the default configuration in my project it stops working.
Any ideas?

**Comment by wmertens** [comment]
Should the configuration even be forced? Coffeelint's docs say that it will automatically look for coffeelint.json and package.json files...

**Comment by nickdima** [comment]
What do you mean by forced? If I have a `coffeelint.json` in my project's root it doesn't work. If I remove it does work.

**Comment by wmertens** [comment]
I mean, the plugin tries to find the config and gives it to coffeelint with -f, but coffeelint should be able to find it itself. I think.

**Comment by nickdima** [comment]
Suggestions?

**Comment by wmertens** [comment]
Remove the config file testing and just let coffeelint figure it out by
itself?

**Comment by AsaAyers** [comment]
Please try again with v0.2.0. linter-coffeelint should now work exactly the same way the coffeelint commandline does. Here are the [CoffeeLint Docs](https://github.com/clutchski/coffeelint/blob/master/doc/user.md) on how to configure your project.

**Comment by nickdima** [comment]
OK, now it works. But there's another problem: if you use the [transforms feature](https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs) it breaks because it doesn't look for the transformer module in the project's npm folder. Installing it in the package's npm folder it worked.

**Comment by AsaAyers** [comment]
Correct. I have a temporary workaround in https://github.com/AtomLinter/linter-coffeelint/issues/25 and I'll be fixing the issue in CoffeeLint.

**Comment by nickdima** [comment]
Great @AsaAyers thanks a lot for your work!

**Comment by febLey** [comment]
I've got the same issue, but the folder with the coffeescript files is symlinked into my project folder:

![screen shot 2015-06-29 at 11 28 48](https://cloud.githubusercontent.com/assets/1727958/8405096/62fa7f9e-1e52-11e5-9a2d-2e419b229ed9.png)

**Comment by nickdima** [comment]
@febLey offtopic: what's the name of the ui and syntax theme you're using?

**Comment by febLey** [comment]
@nickdima It's One Dark for both Syntax and UI
