### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by joefitzgerald** [AtomLinter/linter-coffeelint#28]
[Enter steps to reproduce below:]

1. Open your user configuration in Atom
2. Observe error (although it may be dependent on the config itself)

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/jfitzgerald/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/coffeelint.js:2039

TypeError: Cannot read property '0' of null
  at NoImplicitBraces.module.exports.NoImplicitBraces.lintToken (/Users/jfitzgerald/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/coffeelint.js:2039:42)
  at LexicalLinter.module.exports.LexicalLinter.lintToken (/Users/jfitzgerald/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/coffeelint.js:818:43)
  at LexicalLinter.module.exports.LexicalLinter.lint (/Users/jfitzgerald/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/coffeelint.js:786:19)
  at Object.coffeelint.lint (/Users/jfitzgerald/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/coffeelint.js:311:31)
  at LinterCoffeelint.lintFile (/Users/jfitzgerald/.atom/packages/linter-coffeelint/lib/linter-coffeelint.coffee:49:25)
  at /Users/jfitzgerald/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/jfitzgerald/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -7:59.6 settings-view:open (atom-text-editor.editor)
     -7:51.0 core:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "markdown-format"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "linter-coffeelint": {
    "coffeelintExecutablePath": "/usr/local/bin/coffeelint"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
go-plus, v3.3.1
language-asciidoc, v0.11.1
language-docker, v1.1.3
language-tcl, v0.1.0
linter, v0.12.0
linter-coffeelint, v0.2.0
markdown-table-formatter, v2.5.2
pretty-json, v0.3.2
tabs-to-spaces, v0.9.1

# Dev
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.0.1
go-plus, v3.3.1
```

**Comment by joefitzgerald** [comment]
I removed:

```json
"linter-coffeelint": {
    "coffeelintExecutablePath": "/usr/local/bin/coffeelint"
  }
```

...and am still experiencing the issue.

**Comment by AsaAyers** [comment]
This is actually a bug in CoffeeLint. Would you mind opening an [issue there](https://github.com/clutchski/coffeelint/issues)? It's having trouble parsing something in your code. If you're able to narrow it down to the smallest reproducible file it would be a huge help.

**Comment by joefitzgerald** [comment]
You should consider catching unhandled errors when you call out to CoffeeLint. It's a trivial amount of code that would allow you to handle any unforeseen CoffeeLint issue gracefully (e.g. by displaying your own notification, and preventing people from opening an issue whenever CoffeeLint runs into an issue - that's got to get pretty annoying!).

**Comment by AsaAyers** [comment]
`v0.2.1` wraps calls to CoffeeLint. If there is an error it shows up gracefully as a lint error on line 1 and dumps the info to the console. There's probably a better solution, but this is simple enough and doesn't block atom with an exception.
