### ISSUE TITLE
Coffeelint config setting is ignored

### ISSUE THREAD

**Issue by ide** [AtomLinter/linter-coffeelint#30]
The setting in Atom editor appears to be ignored as of 0.20 or 0.21.

![screenshot 2015-03-31 19 34 07](https://cloud.githubusercontent.com/assets/379606/6933502/f0b8566a-d7dc-11e4-9648-e421ab2672ce.png)

Could you please either bring back support for the setting or remove it from the UI?

**Comment by AsaAyers** [comment]
It has been removed, but Atom generates it anyway if you had a custom value. Just place that coffeelint.json in your project and it'll get picked up. If you insist on global configuration you can also put it in your home.

![selection_001](https://cloud.githubusercontent.com/assets/324999/6933593/67c25eee-d7f7-11e4-8f87-09a92e5b7166.png)

**Comment by ide** [comment]
Thanks for the pointers and quick response. Moving coffeelint.cson to my repo root and removing the entry from Atom's config.cson worked =)
