### ISSUE TITLE
max_line_length can't ignore

### ISSUE THREAD

**Issue by Negaihoshi** [AtomLinter/linter-coffeelint#31]
I use v0.2.1.
I set below setting in coffeelint.json 
```
  "max_line_length": {
    "name": "max_line_length",
    "level": "ignore"
  },
```
But it also show max_line_length message.

**Comment by AsaAyers** [comment]
What does your full coffeelint.json look like, and is it in the root of your project? If the file can't be parsed (because JSON is extra picky) the file will simply be ignored.

**Comment by Negaihoshi** [comment]
Thank you.
I forget put coffeelint.json in my root of project.
My config is work now.
