### ISSUE TITLE
Disabled by default

### ISSUE THREAD

**Issue by tombh** [AtomLinter/linter-coffeelint#39]
I'm not sure what's going on but my linter-coffeelint is disabled by default. If I change this line: https://github.com/AtomLinter/linter-coffeelint/blob/master/lib/init.coffee#L16 then it works again.

I have version 0.12.6 of linter and version 0.3.1 of linter-coffeelint

Is this something to do with the new linter-plus?

**Comment by AsaAyers** [comment]
Sorry, I failed to verify this with the current version of the linter. I thought that function was only called if the new `linter-plus` requested that service. I'll push a fix ASAP

**Comment by AsaAyers** [comment]
I removed that line and published v0.3.2

**Comment by tombh** [comment]
Yay \o/, that did the trick :D Thanks
