### ISSUE TITLE
Restore the Coffeelint Config Path option

### ISSUE THREAD

**Issue by pomutemu** [AtomLinter/linter-coffeelint#44]
Original `coffeelint` can set specify a custom configuration file with a `-f` option.

- http://www.coffeelint.org/#usage

But `linter-coffeelint` hasn't been able to do that since fe160ba2a1c36f22fc5b20ee5cb1ccc23a181818.

why?

I hope to restore the Coffeelint Config Path option.

**Comment by AsaAyers** [comment]
The commit you linked to has your answer.

>  # Your configuration belongs in your project, not your editor.
>  # https://github.com/clutchski/coffeelint/blob/master/doc/user.md

You can either place `coffeelint.json` in your project (usually the root) or you can have a global one in whatever your OS's version of `$HOME/coffeelint.json` is.
