### ISSUE TITLE
is there a way to escape the error shown below - it is covering a lot of screen 

### ISSUE THREAD

**Issue by skandasoft** [AtomLinter/linter-coffeelint#46]
is there a way to escape the error shown below - it is covering a lot of screen ..And I would like to get to it as I get along, not always showing up.

**Comment by AsaAyers** [comment]
Did you forget to attach a screenshot?

**Comment by skandasoft** [comment]
May be I will add 1 more question to this..How can ask linter to not care about indentation/line length (which seems to most of things it showing now..)..I know there is coffeelint.json..but what should i pass and is it enough I store on the project folder...

![image](https://cloud.githubusercontent.com/assets/9875379/8738876/7d236a4c-2bfa-11e5-8a34-ea0c7030a373.png)

as you see in the image the errors are shown..can I escape it(key combination/command) and click on the error count to really show the errors when I want to see it and all other time just see the count of errors..

**Comment by AsaAyers** [comment]
IMO this makes the whole thing worthless, but if you really want it put this in your `coffeelint.json` in the root of your project:

```json
{
  "max_line_length": {
    "level": "ignore"
  },
  "indentation": {
    "level": "ignore"
  }
}
```

**Comment by skandasoft** [comment]
my original question still remains as to is there a way to minimize the error screen and just show the error count??

**Comment by AsaAyers** [comment]
Click the active tab. From your screenshot it reads `File 21`

**Comment by skandasoft** [comment]
?? my question was how to minimize the error which show the lines..I would like to see the error details only if I click on the file 21 and not all the time...

**Comment by skandasoft** [comment]
I think I found linter:togglePanel..I think click on the error would toggle/ esc button will toggle...
