### ISSUE TITLE
Wrong Path supplied to coffeelint/lib/configfinder.js

### ISSUE THREAD

**Issue by de-monkeyz** [AtomLinter/linter-coffeelint#47]
I've discovered an issue when working on coffee files that are in the same directory as the coffeelint.json/package.json file that contains the definition coffeelint configuration. The plugin currently supplies the parent directory of the current file to the configfinder supplied by coffeelint.

However this will cause it to not find the correct file (and return null). To fix the issue you can change the parameter supplied to the finder to `filePath` rather than `origPath` on line 68 of `core.coffee`:

```coffeescript
config = configFinder.getConfig(filePath)
```

Whilst this use case isn't like to occur often. It is a problem in the case where I am using coffeescript to write my Gulpfile.

**Comment by AsaAyers** [comment]
Thanks for the info. I'm fixing it now.
