### ISSUE TITLE
Does coffeelint support cjsx syntax?

### ISSUE THREAD

**Issue by PHELiOX** [AtomLinter/linter-coffeelint#48]

**Comment by AsaAyers** [comment]
you can configure [CoffeeLint to use a transform](https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs).

Seriously, I recommend switching to ES6. Everything related to JSX has much better support than CJSX. The only thing CoffeeLint can do is transform CJSX into valid CoffeeScript, then lint that. You aren't going to be able to control the line length or which style quotes it uses.
