### ISSUE TITLE
Custom config file (.coffeelintrc)

### ISSUE THREAD

**Issue by brunowego** [AtomLinter/linter-coffeelint#51]
Think add a field for custom config file. In my project I change the config file name to .coffeelintrc.

See another discussions about this: https://github.com/clutchski/coffeelint/issues/362

**Comment by AsaAyers** [comment]
No, your configuration belongs in your project. not your editor. When you add this kind of option it requires everyone working on your project to re-configure their editor to match your configuration. The only ways to specify a custom config file is `coffeelint -f` and `$COFFEELINT_CONFIG`. I recommend just accepting the fact that the correct filename is `coffeelint.json`. Rename your file and then nothing else has to change.

**Comment by danielbayley** [comment]
> The only ways to specify a custom config file is `coffeelint -f` and `$COFFEELINT_CONFIG`

Although `linter-coffeescript` seems to ignore `$COFFEELINT_CONFIG ` completely in Atom.

**Comment by Arcanemagus** [comment]
@danielbayley you should file an issue over on that project then, as it has nothing to do with this project.

**Comment by danielbayley** [comment]
> you should file an issue over on that project then, as it has nothing to do with this project.

Which other project? This is `linter-coffeescript`… and since the underlying `coffeelint` binary does successfully use `$COFFEELINT_CONFIG` in absence of a local project one; this leads me to believe the issue is with this package (I checked the console, and the env variable is correct).

**Comment by AsaAyers** [comment]
This project is `linter-coffeelint`. There is a different project named `linter-coffeescript` that only checks for syntax errors.

I'm fairly sure you meant `linter-coffeelint` (this project) each time. Even though I think `$COFFEELINT_CONFIG` is a bad idea [and should be removed](https://github.com/clutchski/coffeelint/issues/366), it should be supported as long as it exists.

**Comment by danielbayley** [comment]
> I'm fairly sure you meant linter-coffeelint (this project) each time.

Ah, I did! My bad…
