### ISSUE TITLE
Allow inline errors to be disabled

### ISSUE THREAD

**Issue by Anaphase** [AtomLinter/linter-coffeelint#54]
I just upgraded my version to 1.1.0 and now I've got these really annoying inline errors:

<img src="https://cloud.githubusercontent.com/assets/2358694/9772398/96692cda-5701-11e5-8d2c-3dd28cbec1a5.png">

These bother me a lot because they popup before I'm even done writing the whole line! Didn't there used to be an option in the config to turn these off and only have footer/line-number-gutter errors?

**Comment by AsaAyers** [comment]
![selection_321](https://cloud.githubusercontent.com/assets/324999/9772715/f67934d0-570b-11e5-8973-ea7c7c1773dc.png)

I think that's the option you're looking for. [Linter](https://github.com/atom-community/linter) is in full control of the UI. `linter-coffeelint` just runs `coffeelint` and reports the list of messages

**Comment by Anaphase** [comment]
Ah, okay I guess that updated too and they changed the defaults or something. Sorry about that!
