### ISSUE TITLE
Update Settings section in README.md?

### ISSUE THREAD

**Issue by objectkit** [AtomLinter/linter-coffeelint#57]
Great plugin, thanks! Following the link in the Settings section of your README, I had been putting my coffeelint.json file in my project, which definitely has its uses for teams, but I wanted a global config to suit my own tastes. Maybe you should note that that you can also put your personal preferences in

_~/.atom/packages/linter-coffeelint/node_modules/coffeelint/coffeelint.json_

(on mac at least). That way coffee-lint will use these preferences when linting...

**Comment by AsaAyers** [comment]
No, you absolutely should not do this. Modifying the package in the place it's installed is just a bad idea.

Modifying that file doesn't even do what you think it does.

**Comment by AsaAyers** [comment]
You should be able to just drop a `coffeelint.json` into your OS's equivilent of a home directory.

https://github.com/clutchski/coffeelint/blob/master/src/configfinder.coffee#L52-L53

I'm not going to recommend it as I consider it bad practice. The rules of your project belong with your project, I don't care if you're a team of 1 or 100.

**Comment by objectkit** [comment]
Thanks for getting back to me- good points- I just wanted to have a central place to co-ordinate coffeelint for use with my projects using Atom... somewhere in the IDE is the only logical place I could think off at the time (new to Atom) and what I did *seemed* to work. I completely agree the home directory is a bad place for it, so thats why I avoided it. And noted the package is not a good idea either! Out of curiosity, apart from the general crap move, what what does that file do thats such a bad idea? Any plans to support a centralised custom location for coffeelint.json apart from the project root? While its good, its a bit of hassle to copy and paste it around and add it to .gitignore. Cheers!

**Comment by AsaAyers** [comment]
If you want a global configuration your only option is to place it in your home. It's the compromise that has already been made a couple years ago.

> Out of curiosity, apart from the general crap move, what what does that file do thats such a bad idea?

linter-coffeelint doesn't read that config file. That is just the config file that governs the source code of coffeelint. I opened a PR to have [npm ignore](https://github.com/clutchski/coffeelint/pull/521) that file, so it will disappear in some future release.

> While its good, its a bit of hassle to copy and paste it around and add it to .gitignore. Cheers!

You should commit your configuration. It belongs with your code.

**Comment by objectkit** [comment]
Good to know the purpose of that config file, shame to learn about the non-customisable location of the global configuration. From my POV, my config belongs with my IDE, not my source code (or my home directory for that matter!), but I see how that is not possible given the other constraints you've pointed out. Thanks anyway.
