### ISSUE TITLE
What happened to the error/warning summary?

### ISSUE THREAD

**Issue by nmccready** [AtomLinter/linter-coffeelint#61]
In an older version of Atom w/ this plugin there used to be a summary of all the errors an warnings for a file. This was superb with little effort needed to navigate a file and find the problems.

Anyway since 1.0.0 or maybe 1.1.0 the summary box has disappeared. Is there anyway to bring this back via settings? Is this a regression due Atom updates.. I just wanted to throw this out there as this feature was awesome and sorely missed.

**Comment by AsaAyers** [comment]
linter-coffeelint has no control over the display of the data. It only provides the raw data for [Linter](https://github.com/atom-community/linter) to display.

**Comment by nmccready** [comment]
Ok, so ideas on what this feature was? IE report it to atom team?

**Comment by AsaAyers** [comment]
![selection_286](https://cloud.githubusercontent.com/assets/324999/12037854/c464b07a-ae20-11e5-8855-72137375939a.png)

This is what I'm seeing. 1.0 was a complete rewrite. None of the UI was kept but replacements have been built for everything. Maybe before reporting to linter, take a look at the settings. For some reason there are a ton of options to customize everything including turning that panel off.

**Comment by nmccready** [comment]
Thank you! Any idea what that panel is called?

**Comment by AsaAyers** [comment]
Based on the setting that turns it off, it seems to be "Error Panel"

**Comment by Arcanemagus** [comment]
@nmccready make sure you have [linter](https://github.com/atom-community/linter) installed and enabled, the settings that control the display of that are in the linter package's settings.
