### ISSUE TITLE
Exception for URLs going to end of line with `max_line_length`?

### ISSUE THREAD

**Issue by brettz9** [AtomLinter/linter-coffeelint#65]
I know other linters (such as markdown) forgive max lines which exceed the designated amount as long as it is due to a URL at the end of a line (with nothing after it).

Could support for this be added, as I need a long URL in the comments...

Thanks!

**Comment by AsaAyers** [comment]
This project is just integration between CoffeeLint and Atom, so this type of request would belong in [coffeelint](https://github.com/clutchski/coffeelint).

This has already been implemented. It looks like the URL needs to be on a line by itself to match the exception. See [max_line_length.coffee](https://github.com/clutchski/coffeelint/blob/master/src/rules/max_line_length.coffee#L6)

**Comment by brettz9** [comment]
Hmm... it's not working for me:
```
# https://example.com/abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg
```

Ok, I can report it there, thanks.

**Comment by AsaAyers** [comment]
Your exact URL works fine for me.

```
asa@asa:/tmp/foo$ cat tmp.coffee 
# Lint your CoffeeScript! alsdkf jlaksdf jlkdsa fjlksad jflkdsa jflksad jflaskdj flkasdj flaksdj f
# https://example.com/abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg
asa@asa:/tmp/foo$ coffeelint --version
1.15.0
asa@asa:/tmp/foo$ coffeelint tmp.coffee 
  ✗ tmp.coffee
     ✗ #1: Line exceeds maximum allowed length. Length is 98, max is 80.

✗ Lint! » 1 error and 0 warnings in 1 file
```

**Comment by brettz9** [comment]
On Atom 1.6.2, with linter 1.11.4 and linter-coffeelint 1.1.2, this URL in my `keymap.cson` gets the error (even tested as such with nothing else in the file). I don't have coffeelint in my path.
