### ISSUE TITLE
indent errors for config.cson

### ISSUE THREAD

**Issue by taoeffect** [AtomLinter/linter-coffeelint#66]
My `config.cson` for Atom gives a bunch of these (for each indentation):

```
Line contains inconsistent indentation. Expected 4 got 2. (Indentation)
```

![screen shot 2016-06-13 at 1 07 25 am](https://cloud.githubusercontent.com/assets/138706/16000781/3fde75d2-3103-11e6-83ff-3cf963480428.jpg)

My tab width is set to 2.

**Comment by AsaAyers** [comment]
Wherever that file is stored, you need to create a `coffeelint.json` and configure coffeelint to use a width of 2.

**Comment by taoeffect** [comment]
This was totally my fault. I had a global (in `$HOME`) coffeelint.json where I'd set 4 as the `indentation`, and simply had forgotten about this. The default indentation is 2, so I was confused as to what was going on.

Thanks!
