### ISSUE TITLE
Add support for coffeescope

### ISSUE THREAD

**Issue by davibe** [AtomLinter/linter-coffeelint#67]
https://github.com/za-creature/coffeescope

It's super, it can detect undefined variables which is a very common error. The problem is that i installed it global but linter-coffeelint does not pick it up. Maybe it needs to be installed inside the atom package ?

**Comment by AsaAyers** [comment]
It needs to be a local dev dependency in your project. Coffeelint should be
too if your project is using it.

**Comment by davibe** [comment]
i have done that. But i don't like it. I like to keep my project clean from things that are needed to edit it (because another developer may use something else). Looking around I see that ppl are doing what you say :/

thank you

**Comment by Arcanemagus** [comment]
Closing as wontfix, if you want additional functionality like that install it locally as suggested.
