### ISSUE TITLE
False positive on modern Coffeescript syntax

### ISSUE THREAD

**Issue by elektronik2k5** [AtomLinter/linter-coffeelint#69]
Current version is based on a version of coffeelint which is over a year old. Quoting the [coffeelint changelog](http://www.coffeelint.org/#changelog): 

> The v1.12.x versions are considered buggy and you should upgrade to v1.13.x if you experience problems

In addition to that, modern syntax (import/export, generators and others), as well as new lint rules aren't supported.

https://github.com/AtomLinter/linter-coffeelint/pull/68 fixes that! :)

**Comment by Arcanemagus** [comment]
Fixed in #70.
