### ISSUE TITLE
How to use coffeelint modules?

### ISSUE THREAD

**Issue by medialwerk** [AtomLinter/linter-coffeelint#80]
Hello,

i want to use the coffeescope2 plugin with coffeelint. If i install coffeelint and coffeescope2 in the global namespace and add the coffeescope2 configuration to the coffeelint.json, coffeelint crashes with the following error:

```
Error: Cannot find module 'coffeescope2' from ...
```

coffeelint.json:
```
 "check_scope": {
   "module": "coffeescope2",
 ...
````

Thanks for your help!

**Comment by AsaAyers** [comment]
Plugins need to be local to your project, it should be in your `devDependencies`. Atom and Node do not share the same global install location.

While `linter-coffeelint` ships with some version of coffeelint, you can can manage the version used by putting `coffeelint` in `devDependencies` too. By making it local any commit hooks, CI scripts, or `npm run lint` (if you configure it) can all use a consistent version. It keeps your team from running into annoying issues where one person has an outdated coffeelint.
