### ISSUE TITLE
Freezes on long files

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-coffeelint#87]
On long files this freezes Atom on Windows 10

**Comment by Arcanemagus** [comment]
The only way to fix this is to move execution to a separate thread, it looks like this provider only uses the built in version so it's not as large of a project as some other providers but it's still somewhat of an undertaking.

**Comment by UziTech** [comment]
It seems like the other linters get around this by using a cli tool. Could we just run coffeelint as a seperate process and parse the output.

It seems like this is the way it was originally #20

**Comment by Arcanemagus** [comment]
That's certainly a possibility, note that currently this uses the `csslint` of the project being linted so the same functionality would need to be included (in however this gets implemented).
