### ISSUE TITLE
CoffeeLint not loaded for .litcoffee files

### ISSUE THREAD

**Issue by joaomlneto** [AtomLinter/linter-coffeelint#89]
Linter won't load `CoffeeLint` for `.litcoffee` files:

```
Platform: darwin
Atom Version: 1.19.1
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
  - js-standard
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.litcoffee
  - markup.raw.block.markdown
  - punctuation.terminator.statement.coffee
```

I'm using `language-coffee-script` for atom language support.

Workaround suggested by @Arcanemagus is to first open a `.coffee` file to load the package, and then `CoffeeLint` works as expected for `.litcoffee` files as well. :)

@Arcanemagus suggested the problem lies within the `activationHooks` in `package.json`.

**Comment by Arcanemagus** [comment]
Hmmm, are you sure that you don't have another package providing "CoffeeScript (literate)" support? `language-coffee-script` is a core package that provides the default support, and works just fine on my machine already.

You can find the name of the package that is providing the grammar for the current file by opening Developer Tools and running this in the Console:

```js
atom.workspace.getActiveTextEditor().getGrammar().packageName
```

**Comment by joaomlneto** [comment]
Whoops, you're right. That line returns `language-iced-coffee-script`. My bad.
